/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package parking.lot.app;

import org.junit.Test;

import com.parkinglot.object.Lot;
import com.parkinglot.object.Lot.LotBuilder;
import com.parkinglot.object.LotType;
import com.parkinglot.object.Receipt;
import com.parkinglot.object.Ticket;
import com.parkinglot.object.Util;
import com.parkinglot.object.VehicleType;

import static org.junit.Assert.*;

import org.junit.Before;

public class AirportParkingLot {

  private Lot lot;

  @Before
  public void setUp() {
    this.lot = new LotBuilder().setLotSizeByVechile(VehicleType.TWO_WHEELER, 200)
        .setLotSizeByVechile(VehicleType.FOUR_WHEELER, 500)
        .setLotSizeByVechile(VehicleType.HEAVY_DUTY, 100).setLotType(LotType.AIRPORT).build();
  }

  @Test
  public void shouldGenerateCorrectFee() {
    Ticket ticket1 = lot.park("motorcycle");
    Ticket ticket2 = lot.park("motorcycle");
    Ticket ticket3 = lot.park("motorcycle");
    Ticket ticket4 = lot.park("car");
    Ticket ticket5 = lot.park("suv");
    Ticket ticket6 = lot.park("car");
    Receipt receipt1 =
        lot.unPark(ticket1, Util.addHoursToJavaUtilDate(ticket1.getEntryDateTime(), 55));
    Receipt receipt2 =
        lot.unPark(ticket2, Util.addHoursToJavaUtilDate(ticket2.getEntryDateTime(), 899));
    Receipt receipt3 =
        lot.unPark(ticket3, Util.addHoursToJavaUtilDate(ticket3.getEntryDateTime(), 2160));
    Receipt receipt4 =
        lot.unPark(ticket4, Util.addHoursToJavaUtilDate(ticket3.getEntryDateTime(), 50));
    Receipt receipt5 =
        lot.unPark(ticket5, Util.addHoursToJavaUtilDate(ticket1.getEntryDateTime(), 1439));
    Receipt receipt6 =
        lot.unPark(ticket6, Util.addHoursToJavaUtilDate(ticket2.getEntryDateTime(), 4380));
    assertEquals(0, receipt1.getFees());
    assertEquals(60, receipt2.getFees());
    assertEquals(160, receipt3.getFees());
    assertEquals(60, receipt4.getFees());
    assertEquals(80, receipt5.getFees());
    assertEquals(400, receipt6.getFees());
  }



}
