/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package parking.lot.app;

import org.junit.Test;

import com.parkinglot.object.Lot;
import com.parkinglot.object.Lot.LotBuilder;
import com.parkinglot.object.LotType;
import com.parkinglot.object.Receipt;
import com.parkinglot.object.Ticket;
import com.parkinglot.object.Util;
import com.parkinglot.object.VehicleType;

import static org.junit.Assert.*;

import org.junit.Before;

public class MallParkingLotTest {

  private Lot lot;

  @Before
  public void setUp() {
    this.lot = new LotBuilder().setLotSizeByVechile(VehicleType.TWO_WHEELER, 100)
        .setLotSizeByVechile(VehicleType.FOUR_WHEELER, 80)
        .setLotSizeByVechile(VehicleType.HEAVY_DUTY, 10).setLotType(LotType.MALL).build();
  }

  @Test
  public void shouldGenerateCorrectFee() {
    Ticket ticket1 = lot.park("motorcycle");
    Ticket ticket2 = lot.park("car");
    Ticket ticket3 = lot.park("truck");
    Receipt receipt1 =
        lot.unPark(ticket1, Util.addHoursToJavaUtilDate(ticket1.getEntryDateTime(), 210));
    Receipt receipt2 =
        lot.unPark(ticket2, Util.addHoursToJavaUtilDate(ticket2.getEntryDateTime(), 361));
    Receipt receipt3 =
        lot.unPark(ticket3, Util.addHoursToJavaUtilDate(ticket3.getEntryDateTime(), 119));
    assertEquals(40, receipt1.getFees());
    assertEquals(140, receipt2.getFees());
    assertEquals(100, receipt3.getFees());
  }


}
