/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package parking.lot.app;

import org.junit.Test;

import com.parkinglot.object.Lot;
import com.parkinglot.object.Lot.LotBuilder;
import com.parkinglot.object.LotType;
import com.parkinglot.object.Receipt;
import com.parkinglot.object.Ticket;
import com.parkinglot.object.Util;
import com.parkinglot.object.VehicleType;

import static org.junit.Assert.*;

import org.junit.Before;

public class StadiumParkingLotTest {

  private Lot lot;

  @Before
  public void setUp() {
    this.lot = new LotBuilder().setLotSizeByVechile(VehicleType.TWO_WHEELER, 1000)
        .setLotSizeByVechile(VehicleType.FOUR_WHEELER, 1500).setLotType(LotType.STADIUM).build();
  }

  @Test
  public void shouldGenerateCorrectFee() {
    Ticket ticket1 = lot.park("motorcycle");
    Ticket ticket2 = lot.park("motorcycle");
    Ticket ticket3 = lot.park("suv");
    Ticket ticket4 = lot.park("car");
    Receipt receipt1 =
        lot.unPark(ticket1, Util.addHoursToJavaUtilDate(ticket1.getEntryDateTime(), 220));
    Receipt receipt2 =
        lot.unPark(ticket2, Util.addHoursToJavaUtilDate(ticket2.getEntryDateTime(), 899));
    Receipt receipt3 =
        lot.unPark(ticket3, Util.addHoursToJavaUtilDate(ticket3.getEntryDateTime(), 690));
    Receipt receipt4 =
        lot.unPark(ticket4, Util.addHoursToJavaUtilDate(ticket3.getEntryDateTime(), 785));
    assertEquals(30, receipt1.getFees());
    assertEquals(390, receipt2.getFees());
    assertEquals(180, receipt3.getFees());
    assertEquals(580, receipt4.getFees());
  }
  
  
  
 

}
